spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${MONGO_ACCESS}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    mapper:
      accept-case-insensitive-properties: true